export interface StateFormsEntry {
  state: string
  slug: string
  court: string
  url: string
  notes: string
}

export const STATE_FORMS_DATA: StateFormsEntry[] = [
  { state: 'Alabama', slug: 'alabama', court: 'Alabama Law Help', url: 'https://alabamalawhelp.org/issues/family-and-domestic/divorce', notes: 'Free forms + guides; official site: alacourt.gov' },
  { state: 'Alaska', slug: 'alaska', court: 'Alaska Courts Self-Help', url: 'https://courts.alaska.gov/selfhelp/family/divorce.htm', notes: 'Official forms + step-by-step instructions' },
  { state: 'Arizona', slug: 'arizona', court: 'AZ Courts Self Service Center', url: 'https://selfservecenter.azcourts.gov', notes: 'Guided interview generates completed forms — best in class' },
  { state: 'Arkansas', slug: 'arkansas', court: 'Arkansas Judiciary', url: 'https://arcourts.gov/courts/district-court/forms', notes: 'Forms + eFlex e-filing system' },
  { state: 'California', slug: 'california', court: 'CA Courts Self-Help', url: 'https://selfhelp.courts.ca.gov/divorce', notes: 'Official FL-series forms; guided process' },
  { state: 'Colorado', slug: 'colorado', court: 'Colorado Judicial Branch (JDF Forms)', url: 'https://coloradojudicialaccess.org', notes: 'JDF-numbered forms; excellent organization' },
  { state: 'Connecticut', slug: 'connecticut', court: 'CT Judicial Branch Webforms', url: 'https://jud.ct.gov/webforms', notes: 'JD-FM series; complete family law forms' },
  { state: 'Delaware', slug: 'delaware', court: 'Delaware Courts Self-Help', url: 'https://courts.delaware.gov/selfhelp', notes: 'Family Court forms and instructions' },
  { state: 'Florida', slug: 'florida', court: 'Florida Courts Self-Help', url: 'https://www.flcourts.gov/Resources-Services/Court-Improvement/Family-Courts/Family-Law-Self-Help-Information', notes: 'Mandatory financial disclosure forms included' },
  { state: 'Georgia', slug: 'georgia', court: 'Georgia Courts DIY Portal', url: 'https://diy.georgiacourts.gov', notes: 'Excellent guided interview; free' },
  { state: 'Hawaii', slug: 'hawaii', court: 'Hawaii State Judiciary', url: 'https://www.courts.state.hi.us/self-help/courts/forms/oahu/family', notes: 'Check your specific circuit (island); forms vary' },
  { state: 'Idaho', slug: 'idaho', court: 'Idaho Courts Self-Help', url: 'https://isc.idaho.gov/family-law-self-help', notes: 'Free forms; community property state' },
  { state: 'Illinois', slug: 'illinois', court: 'Illinois Legal Aid Online', url: 'https://www.illinoislegalaid.org/legal-information/divorce-guide', notes: 'Document assembly + guides; ilcourts.info for official forms' },
  { state: 'Indiana', slug: 'indiana', court: 'Indiana Courts Self-Service', url: 'https://courts.in.gov/selfservice', notes: 'Well-organized state forms' },
  { state: 'Iowa', slug: 'iowa', court: 'Iowa Courts eForms', url: 'https://www.iowacourts.gov/for-the-public/court-forms/family-law', notes: 'Electronic divorce system for childless cases' },
  { state: 'Kansas', slug: 'kansas', court: 'Kansas Courts Self-Help', url: 'https://www.kscourts.org/Resources/Self-Help-Center', notes: 'District court forms by county' },
  { state: 'Kentucky', slug: 'kentucky', court: 'Kentucky Courts AOC Forms', url: 'https://courts.ky.gov/forms', notes: 'AOC-numbered forms; paper filing for self-reps' },
  { state: 'Louisiana', slug: 'louisiana', court: 'Louisiana Law Help', url: 'https://louisianalawhelp.org/issues/family/divorce', notes: 'Best free resource; parish-specific guidance' },
  { state: 'Maine', slug: 'maine', court: 'Pine Tree Legal Assistance', url: 'https://www.ptla.org/divorce', notes: 'Excellent free DIY guides; courts.maine.gov for official forms' },
  { state: 'Maryland', slug: 'maryland', court: 'Maryland Courts Self-Help', url: 'https://mdcourts.gov/legalhelp/familylawforms', notes: 'Post-2023 reform forms; mutual consent path' },
  { state: 'Massachusetts', slug: 'massachusetts', court: 'Mass.gov Divorce Forms', url: 'https://www.mass.gov/divorce-forms', notes: '1A/1B forms; Financial Statement required' },
  { state: 'Michigan', slug: 'michigan', court: 'Michigan Courts Self-Help', url: 'https://courts.michigan.gov/self-help/center/pages/family-division-forms.aspx', notes: 'SCAO forms; statewide standardized' },
  { state: 'Minnesota', slug: 'minnesota', court: 'MN Courts Self-Help Forms', url: 'https://www.mncourts.gov/GetForms.aspx', notes: 'FA-series forms; select Family → Divorce' },
  { state: 'Mississippi', slug: 'mississippi', court: 'Mississippi Courts', url: 'https://courts.ms.gov/legal-resources/forms/forms.html', notes: 'Chancery Court forms; joint filing for no-fault' },
  { state: 'Missouri', slug: 'missouri', court: 'Missouri Courts Self-Help', url: 'https://courts.mo.gov/page.jsp?id=105', notes: 'Includes Form 14 for child support' },
  { state: 'Montana', slug: 'montana', court: 'Montana Courts', url: 'https://courts.mt.gov/Self_Help/Family_Law', notes: 'District Court family law forms' },
  { state: 'Nebraska', slug: 'nebraska', court: 'Nebraska Legal Help', url: 'https://nebraskalegalhelp.org/divorce', notes: 'supremecourt.ne.gov for official forms' },
  { state: 'Nevada', slug: 'nevada', court: 'Nevada Self-Help Center', url: 'https://www.nevadalawhelp.org/issues/divorce', notes: 'Clark County: clarkcountycourts.us/self-help' },
  { state: 'New Hampshire', slug: 'new-hampshire', court: 'NH Courts Family Forms', url: 'https://www.courts.state.nh.us/forms/nhjb-forms.htm', notes: 'NHJB-series forms; joint petition available' },
  { state: 'New Jersey', slug: 'new-jersey', court: 'NJ Courts Self-Help', url: 'https://njcourts.gov/selfhelp/family', notes: 'FM forms; CIS (financial disclosure) required' },
  { state: 'New Mexico', slug: 'new-mexico', court: 'NM Courts Self-Help', url: 'https://nmcourts.gov/self-help-center', notes: 'Community property; no waiting period' },
  { state: 'New York', slug: 'new-york', court: 'NY Courts UD Forms', url: 'https://www.nycourts.gov/divorce/index.shtml', notes: 'Uncontested Divorce (UD) packet; county-specific supplements' },
  { state: 'North Carolina', slug: 'north-carolina', court: 'NC Courts Self-Help', url: 'https://www.nccourts.gov/help-topics/family-and-domestic/divorce', notes: '1-year separation required before filing' },
  { state: 'North Dakota', slug: 'north-dakota', court: 'ND Courts Self-Help', url: 'https://www.ndcourts.gov/legal-self-help/family-law/divorce', notes: '$80 filing fee; no waiting period' },
  { state: 'Ohio', slug: 'ohio', court: 'Ohio Legal Help', url: 'https://www.ohiolegalhelp.org/topic/divorce-dissolution', notes: 'Dissolution Form Assistant; standardized SCAO forms' },
  { state: 'Oklahoma', slug: 'oklahoma', court: 'Oklahoma Law Help', url: 'https://www.oklaw.org/issues/family/divorce-dissolution', notes: '10-day wait (no children); OSCN.net for court records' },
  { state: 'Oregon', slug: 'oregon', court: 'Oregon Courts OJD Forms', url: 'https://www.courts.oregon.gov/forms/Pages/default.aspx', notes: 'OJD packets by scenario; co-petition option' },
  { state: 'Pennsylvania', slug: 'pennsylvania', court: 'PA Courts Self-Help', url: 'https://www.pacourts.us/learn/representing-yourself', notes: 'Prothonotary files; equitable distribution separate claim' },
  { state: 'Rhode Island', slug: 'rhode-island', court: 'RI Family Court', url: 'https://www.courts.ri.gov/Courts/FamilyCourt/Pages/Forms.aspx', notes: 'Family Court handles all divorce cases' },
  { state: 'South Carolina', slug: 'south-carolina', court: 'SC Courts Self-Help', url: 'https://sccourts.org/selfhelp', notes: '1-year separation for no-fault; Family Court' },
  { state: 'South Dakota', slug: 'south-dakota', court: 'SD Unified Judicial System', url: 'https://ujs.sd.gov/self_help/family.aspx', notes: 'No residency minimum; no waiting period' },
  { state: 'Tennessee', slug: 'tennessee', court: 'TN Courts', url: 'https://tncourts.gov/programs-and-services/court-system/family-law', notes: 'MDA required; check Circuit vs. Chancery Court' },
  { state: 'Texas', slug: 'texas', court: 'Texas Law Help', url: 'https://texaslawhelp.org/article/getting-a-divorce-in-texas', notes: 'Official portal; excellent step-by-step guidance' },
  { state: 'Utah', slug: 'utah', court: 'Utah Courts MyPaperwork', url: 'https://www.utcourts.gov/en/self-help/divorce.html', notes: 'MyPaperwork system generates customized forms ($20)' },
  { state: 'Vermont', slug: 'vermont', court: 'Vermont Judiciary', url: 'https://www.vermontjudiciary.org/family/divorce', notes: 'Family Court; very low fees (~$100)' },
  { state: 'Virginia', slug: 'virginia', court: 'VA Courts Self-Help', url: 'https://www.vacourts.gov/courts/circuit/resources/circuit_selfhelp.pdf', notes: 'No statewide forms — check your Circuit Court' },
  { state: 'Washington', slug: 'washington', court: 'WA Courts Forms', url: 'https://www.courts.wa.gov/forms/?fa=forms.contribute&formID=13', notes: 'DR-series forms; excellent free system' },
  { state: 'West Virginia', slug: 'west-virginia', court: 'WV Courts Self-Help', url: 'https://www.courtswv.gov/public-resources/court-forms.html', notes: 'SCA-FC forms; Family Court system' },
  { state: 'Wisconsin', slug: 'wisconsin', court: 'WI Courts Forms', url: 'https://www.wicourts.gov/formdisplay', notes: 'FA-series forms; community property state' },
  { state: 'Wyoming', slug: 'wyoming', court: 'Wyoming Courts Self-Help', url: 'https://www.courts.state.wy.us/court-self-help', notes: 'Very low fees ($75–$100); short residency (60 days)' },
]
